server:
  port: 9980

spring:

  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    username: sa
    password:

  batch:
    job:
      enabled: false # CommandLineRunner ?? ??
        # CommandLineRunner? ?????? ????? ?? ??? ??? ? ??? ??? ??? ???.
      # ????? ??? ??? ??? ????? ???? ??? ????? ??
      names: ${job.name:NONE}
